export const mapOrderFromDB = (dbRow: any) => ({
  id: dbRow.id,
  customerId: dbRow.customer_id,
  customerNome: dbRow.customers?.nome || 'Cliente Desconhecido',
  customerTelefone: dbRow.customers?.telefone || '',
  numeroOs: dbRow.numero_os,
  status: dbRow.status,
  deviceLabel: dbRow.device_label,
  problemaRelatado: dbRow.problema_relatado,
  technicianId: dbRow.technician_id,
  technicianNome: dbRow.technician_nome || 'N/A',
  valorMaoObra: Number(dbRow.valor_mao_obra || 0),
  valorPecas: Number(dbRow.valor_pecas || 0),
  criadoEm: dbRow.criado_em,
  atualizadoEm: dbRow.atualizado_em,
  deviceId: dbRow.device_id,
  deviceTipo: dbRow.device_tipo,
  horasAbertas: Number(dbRow.horas_abertas || 0),
  fotosCheckin: dbRow.fotos_checkin || [],
  checklistItens: dbRow.checklist_itens || [],
  assinaturaUrl: dbRow.assinatura_url,
  aprovadoEm: dbRow.aprovado_em,
  garantiaDias: Number(dbRow.garantia_dias || 0),
  garantiaExpiraEm: dbRow.garantia_expira_em,
  diagnostico: dbRow.diagnostico,
  solucao: dbRow.solucao,
  observacoes: dbRow.observacoes,
});

export const mapOrderToDB = (appModel: any, tenantId: string) => ({
  tenant_id: tenantId,
  customer_id: appModel.customerId,
  device_label: appModel.deviceLabel,
  problema_relatado: appModel.problemaRelatado,
  valor_mao_obra: appModel.valorMaoObra,
  valor_pecas: appModel.valorPecas,
  status: appModel.status,
  technician_id: appModel.technicianId,
  numero_os: appModel.numeroOs,
});
